system: radiusd
verson: 1.0
bas_host_check: false
bas_default_secret: '123456'
mysql:
    maxusage: 10
    host: 'localhost'
    user: 'root'
    passwd: 'root'
    db: 'slcrms'
    charset: "utf8"
       
